---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.nameOverride }}
    type: infra
