name: Test and publish service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # optional, if you want manual runs from the Actions tab

jobs:
  test:
    uses: yeencloud/dpl-ci/.github/workflows/test.yml@main

  todo-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create issues from TODOs
        uses: alstr/todo-to-issue-action@v5.1.11

  build-and-publish:
    needs: test
    uses: yeencloud/dpl-ci/.github/workflows/package.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}