name: Test and publish service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # optional, if you want manual runs from the Actions tab

jobs:
  test:
    uses: yeencloud/dpl-ci/.github/workflows/test.yml@main

  build-and-publish:
    needs: test
    uses: yeencloud/dpl-ci/.github/workflows/package.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}